import React, { useState } from 'react';
import Select from 'react-select';
import './QuizIntro.css'; // Ensure this file includes the styles provided
import { useNavigate } from 'react-router-dom';

const QuizIntro = () => {
  const [selectedTopics, setSelectedTopics] = useState([]);
  const [difficulty, setDifficulty] = useState('easy');
  const [isDisclaimerVisible, setIsDisclaimerVisible] = useState(true);
  const navigate = useNavigate();

  const handleTopicChange = (selectedOptions) => {
    setSelectedTopics(selectedOptions || []);
  };

  const handleSubmit = (e) => {
    e.preventDefault();
    const quizTopics = selectedTopics.map(option => option.value);
    console.log('Quiz Topics:', quizTopics);
    console.log('Difficulty:', difficulty);
    navigate('/AI', { state: { topicarr: quizTopics, levelarr: difficulty } });
  };

  const closeDisclaimer = () => {
    setIsDisclaimerVisible(false);
  };

  const topicOptions = [
    { value: 'CPP', label: 'CPP' },
    { value: 'JAVA', label: 'JAVA' },
    { value: 'PYTHON', label: 'PYTHON' },
    { value: 'APTITUDE', label: 'APTITUDE' },
    // Add more options as needed
  ];

  return (
    <div className='FRM-Quiz-Intro'>
      {isDisclaimerVisible && (
        <div className="disclaimer-popup">
          <div className="disclaimer-content">
            <h2 style={{ fontSize: '24px' }}>Disclaimer</h2>
            <p>1. Ask the user for what topic they prefer for the quiz and its difficulty level.</p>
            <p>2. The questions and their respective 4 options and the correct option are generated by an Intelligence (GEMINI).</p>
            <p>3. The user is supposed to answer the questions from the 4 options provided.</p>
            <p>4. The answer is verified after clicking the submit button by comparing it to the correct option.</p>
            <p>5. It will display the correct and incorrect answers based on your selection and calculate your score.</p>
            <p>6. After completion, it will show your performance.</p>
            <button className="disclaimer-close-button" onClick={closeDisclaimer}>Close</button>
          </div>
        </div>
      )}
      <div className="FRM-container">
        <form onSubmit={handleSubmit} className="FRM-form">
          <div className="FRM-form-group">
            <label htmlFor="quizTopic" className="FRM-label">Quiz Topics:</label>
            <Select
              id="quizTopic"
              isMulti
              options={topicOptions}
              value={selectedTopics}
              onChange={handleTopicChange}
              className="FRM-select"
            />
          </div>
          <div className="FRM-form-group">
            <label htmlFor="difficulty" className="FRM-label">Difficulty:</label>
            <select
              id="difficulty"
              className="FRM-select"
              value={difficulty}
              onChange={(e) => setDifficulty(e.target.value)}
            >
              <option value="easy">Easy</option>
              <option value="medium">Medium</option>
              <option value="hard">Hard</option>
            </select>
          </div>
          <button type="submit" className="FRM-button">Submit</button>
        </form>
      </div>
    </div>
  );
};

export default QuizIntro;
